// src/components/section2/questions.js
export const section2Questions = [
    {
      key: "gender",
      title: "Your Gender",
      type: "single", // radio
      options: [
        { value: "male", label: "Male" },
        { value: "female", label: "Female" },
        { value: "non_binary", label: "Non-binary" },
        { value: "trans_expansive", label: "Trans / Gender-expansive" },
        { value: "other", label: "Other" },
      ],
      otherKey: "gender_other",
    },
    {
      key: "attraction_style",
      title: "What’s your attraction style or sexuality vibe?",
      helper:
        "(Helps us match your movie kisses, crushes, and chaotic soul connections.)",
      type: "multi", // checkboxes
      options: [
        { value: "queer", label: "🌈 Queer and thriving" },
        { value: "attracted_men", label: "💋 Attracted to men" },
        { value: "attracted_women", label: "💅 Attracted to women" },
        { value: "love_across_spectrum", label: "💞 I love across the spectrum" },
        { value: "bi_pan_switch", label: "🌪 Bi / Pan / Switch energy" },
        { value: "demi_sapio", label: "👁 Demisexual / Sapiosexual" },
        { value: "asexual", label: "🧊 Asexual / No thanks, I’m here for plot" },
        { value: "still_figuring", label: "🤷 Still figuring it out" },
        { value: "dont_label", label: "🌀 I don’t label it" },
        { value: "none_define", label: "🧬 None of the above — I’ll define it" },
        { value: "steamy_anything", label: "🔥 I love anything steamy…" },
        { value: "love_is_love", label: "🤖 Human, alien, AI, ghost — love is love" },
        { value: "other", label: "Other" },
      ],
      otherKey: "attraction_style_other",
    },
    {
      key: "love_o_meter",
      title: "❤ Where would you place yourself on the Movie Love-o-Meter?",
      subtitle: "(Pick what feels most like you)",
      type: "single",
      options: [
        { value: "cinephile", label: "Cinephile Supreme…" },
        { value: "movie_lover", label: "Movie Lover…" },
        { value: "time_poor", label: "Time-Poor Watcher…" },
        { value: "streaming_vortex", label: "Streaming Vortex…" },
        { value: "popcorn_only", label: "Popcorn-Only Viewer…" },
        { value: "sleepy_streamer", label: "Sleepy Streamer…" },
        { value: "recovering_binger", label: "Recovering Binger…" },
        { value: "lost_in_scroll", label: "Lost in the Scroll…" },
        { value: "other", label: "Other" },
      ],
      otherKey: "love_o_meter_other",
    },
    {
      key: "life_role",
      title: "In the movie of your life… what role do you play?",
      subtitle:
        "Pick the one(s) that best describe how you show up — not on screen, but in real life.",
      type: "multi",
      options: [
        { value: "rescuer", label: "🛟 The Rescuer…" },
        { value: "disruptor", label: "🌪 The Chaotic Disruptor…" },
        { value: "outsider", label: "🌸 The Dreamy Outsider…" },
        { value: "overachiever", label: "🧠 The Overachiever / Golden Child…" },
        { value: "observer", label: "👀 The Mysterious Observer…" },
        { value: "ride_or_die", label: "🔥 The Ride-or-Die…" },
        { value: "comic_relief", label: "😌 The Comic Relief…" },
        { value: "wanderer", label: "🧳 The Wanderer…" },
        { value: "mirror", label: "👥 The Mirror…" },
        { value: "audience", label: "🎟 Just here for the popcorn…" },
        { value: "other", label: "Other" },
      ],
      otherKey: "life_role_other",
    },
    {
      key: "escapism_style",
      title: "Your Emotional Escapism Style?",
      subtitle: "How do you use movies to deal (or not deal) with your emotions?",
      type: "multi",
      options: [
        { value: "heartbreak_healer", label: "💔 Heartbreak Healer…" },
        { value: "hangover_hero", label: "🤕 Hangover Hero…" },
        { value: "floodgate", label: "🌊 Emotional Floodgate…" },
        { value: "analyzer", label: "🧠 Chaos Analyzer…" },
        { value: "cozy_comedown", label: "🧸 Cozy Comedown…" },
        { value: "creative_kickstart", label: "🔥 Creative Kickstart…" },
        { value: "romance_igniter", label: "💘 Romance Igniter…" },
        { value: "distraction", label: "🎭 Emotional Distraction…" },
        { value: "romanticizer", label: "✨ Life Romanticizer…" },
        { value: "beauty_seeker", label: "🪐 Beauty Seeker…" },
        { value: "control_watcher", label: "🎮 Control Watcher…" },
        { value: "people_decoder", label: "👤 People Decoder…" },
        { value: "offline", label: "💨 Emotionally Offline…" },
        { value: "ambience_only", label: "🎧 Ambience-Only Watcher…" },
        { value: "other", label: "Other" },
      ],
      otherKey: "escapism_style_other",
    },
    {
      key: "first_obsession",
      title: "👀 Who was your first cinematic obsession or role model?",
      subtitle:
        "That one character, actor, or moment that rewired your brain. (Free text)",
      type: "text",
      otherKey: "first_obsession_text",
    },
  ];